"""
ATC level-4 prefix -> patient-friendly Romanian indication.

Curated from WHO ATC index + Romanian pharmacy product descriptions.
Used by enrichment scripts to add searchable lay-language symptoms
to medicines whose RCP doesn't expose them clearly.

Coverage target: top OTC categories. Long-tail medicines fall back
to the regulatory `therapeutic_action` text from ANMDM.
"""

from __future__ import annotations

ATC4_INDICATIONS: dict[str, dict] = {
    # --- Analgesics / antipyretics / NSAIDs ---
    "N02BE": {"category": "Durere și febră",
              "symptoms": ["durere de cap", "febră", "durere ușoară", "durere moderată", "stare gripală"],
              "description": "Analgezic și antipiretic pentru durere ușoară până la moderată și febră."},
    "N02BA": {"category": "Durere și febră",
              "symptoms": ["durere de cap", "febră", "durere musculară"],
              "description": "Acid acetilsalicilic pentru durere ușoară și febră."},
    "M01AE": {"category": "Durere și inflamație",
              "symptoms": ["durere de cap", "durere musculară", "durere articulară", "febră", "inflamație", "menstruație dureroasă"],
              "description": "Antiinflamator nesteroidian pentru durere și inflamație."},
    "M02AA": {"category": "Durere musculo-articulară",
              "symptoms": ["dureri musculare", "dureri articulare", "lovituri", "entorsă", "contractură"],
              "description": "Antiinflamator topic pentru aplicare locală pe dureri musculare și articulare."},
    "M01AB": {"category": "Durere și inflamație",
              "symptoms": ["durere", "inflamație articulară", "artrită"],
              "description": "Antiinflamator nesteroidian pentru tratamentul durerii și al inflamației."},
    "M01AH": {"category": "Durere și inflamație",
              "symptoms": ["durere", "inflamație"],
              "description": "Inhibitor selectiv COX-2 pentru durere și inflamație."},
    # --- Cough & cold (R series) ---
    "R05CB": {"category": "Tuse productivă",
              "symptoms": ["tuse productivă", "tuse cu secreții", "secreții bronșice", "expectorație dificilă"],
              "description": "Mucolitic care fluidifică secrețiile bronșice pentru a ușura expectorația."},
    "R05CA": {"category": "Tuse productivă",
              "symptoms": ["tuse productivă", "secreții bronșice", "tuse cu mucozități"],
              "description": "Expectorant care ușurează eliminarea secrețiilor."},
    "R05DA": {"category": "Tuse seacă",
              "symptoms": ["tuse seacă", "tuse iritativă", "tuse nocturnă"],
              "description": "Antitusiv pentru tuse seacă, iritativă, fără secreții."},
    "R05X":  {"category": "Răceală și gripă",
              "symptoms": ["răceală", "gripă", "stare gripală", "febră", "congestie nazală", "durere de cap"],
              "description": "Combinație pentru simptome multiple de răceală și gripă."},
    "R01AA": {"category": "Congestie nazală",
              "symptoms": ["nas înfundat", "congestie nazală", "rinită", "secreții nazale"],
              "description": "Decongestionant nazal topic pentru ușurarea respirației pe nas."},
    "R01AB": {"category": "Congestie nazală",
              "symptoms": ["nas înfundat", "congestie nazală", "rinită"],
              "description": "Decongestionant simpatomimetic topic."},
    "R01AX": {"category": "Afecțiuni nazale",
              "symptoms": ["uscăciune nazală", "rinită", "secreții nazale"],
              "description": "Tratament topic pentru afecțiuni ale mucoasei nazale."},
    "R01BA": {"category": "Răceală cu congestie",
              "symptoms": ["nas înfundat", "răceală", "stare gripală", "congestie sinuzală"],
              "description": "Decongestionant sistemic pentru răceală cu congestie nazală pronunțată."},
    "R02AA": {"category": "Afecțiuni gât",
              "symptoms": ["durere în gât", "iritație gât", "amigdalită", "faringită"],
              "description": "Antiseptic local pentru iritații și infecții ale gâtului."},
    "R02AX": {"category": "Afecțiuni gât și cavitate orală",
              "symptoms": ["durere în gât", "iritație gât", "stomatită", "afte bucale"],
              "description": "Antiinflamator și antiseptic pentru durere și iritații în gât și cavitate orală."},
    "R02AD": {"category": "Afecțiuni gât",
              "symptoms": ["durere în gât", "iritație"],
              "description": "Anestezic local pentru durere în gât."},
    "R06AX": {"category": "Alergii",
              "symptoms": ["alergie", "rinită alergică", "urticarie", "mâncărime", "ochi roșii alergici"],
              "description": "Antihistaminic non-sedativ pentru reacții alergice sezoniere și cronice."},
    "R06AB": {"category": "Alergii",
              "symptoms": ["alergie", "urticarie", "mâncărime"],
              "description": "Antihistaminic clasic pentru reacții alergice."},
    "R06AE": {"category": "Alergii",
              "symptoms": ["alergie", "rinită alergică", "urticarie"],
              "description": "Antihistaminic pentru reacții alergice."},
    # --- Digestive (A series) ---
    "A02BX": {"category": "Reflux și arsuri",
              "symptoms": ["arsuri stomac", "reflux", "regurgitații acide", "indigestie"],
              "description": "Tratament al refluxului gastroesofagian prin formarea unei bariere mecanice."},
    "A02BC": {"category": "Hiperaciditate gastrică",
              "symptoms": ["arsuri stomac", "reflux", "ulcer", "indigestie acidă"],
              "description": "Inhibitor al pompei de protoni pentru reducerea acidității gastrice."},
    "A02AD": {"category": "Reflux și arsuri",
              "symptoms": ["arsuri stomac", "reflux", "indigestie"],
              "description": "Antiacid pentru neutralizarea acidității gastrice."},
    "A03AD": {"category": "Crampe digestive",
              "symptoms": ["colici abdominale", "crampe", "dureri menstruale", "spasme"],
              "description": "Antispastic pentru crampe abdominale și colici."},
    "A03AX": {"category": "Tulburări digestive",
              "symptoms": ["balonare", "indigestie", "dispepsie", "greață ușoară"],
              "description": "Tratament al tulburărilor funcționale digestive."},
    "A06AB": {"category": "Constipație",
              "symptoms": ["constipație", "tranzit lent"],
              "description": "Laxativ stimulent pentru constipație ocazională."},
    "A06AD": {"category": "Constipație",
              "symptoms": ["constipație", "evacuare dificilă"],
              "description": "Laxativ osmotic pentru constipație."},
    "A07DA": {"category": "Diaree",
              "symptoms": ["diaree", "scaune frecvente moi"],
              "description": "Antidiareic care reduce motilitatea intestinală."},
    "A07BA": {"category": "Diaree",
              "symptoms": ["diaree", "intoxicație alimentară ușoară"],
              "description": "Adsorbant intestinal pentru episoade diareice."},
    "A09AA": {"category": "Tulburări digestive",
              "symptoms": ["digestie dificilă", "balonare după masă", "insuficiență pancreatică"],
              "description": "Enzime digestive de substituție pentru insuficiență pancreatică sau digestie dificilă."},
    "A05AX": {"category": "Tulburări biliare",
              "symptoms": ["digestie dificilă", "disconfort hepatic", "balonare"],
              "description": "Tratament al disconfortului hepato-biliar."},
    # --- Antiplatelet (cardio prevention) ---
    "B01AC": {"category": "Prevenție cardiovasculară",
              "symptoms": ["prevenție infarct", "prevenție AVC", "antiagregant"],
              "description": "Antiagregant plachetar la doze mici pentru prevenția evenimentelor cardiovasculare."},
    # --- Dermatologic ---
    "D01AC": {"category": "Micoze cutanate",
              "symptoms": ["micoză piele", "ciuperca piciorului", "pecingine", "mâncărime fungică"],
              "description": "Antifungic topic imidazolic pentru micoze ale pielii."},
    "D01AE": {"category": "Micoze cutanate",
              "symptoms": ["micoză piele", "ciuperca piciorului", "candidoză cutanată"],
              "description": "Antifungic topic pentru micoze cutanate."},
    "D04AA": {"category": "Mâncărimi piele",
              "symptoms": ["mâncărime", "înțepături insecte", "urticarie locală"],
              "description": "Antihistaminic topic pentru mâncărimi și înțepături."},
    "D06AX": {"category": "Infecții cutanate",
              "symptoms": ["răni mici suprainfectate", "infecție piele superficială"],
              "description": "Antibiotic topic pentru infecții cutanate superficiale."},
    "D08AC": {"category": "Antiseptic cutanat",
              "symptoms": ["dezinfecție răni", "antiseptic"],
              "description": "Antiseptic local pentru curățarea rănilor."},
    "D11AX": {"category": "Căderea părului",
              "symptoms": ["căderea părului", "alopecie"],
              "description": "Tratament topic pentru căderea părului de tip androgenetic."},
    # --- Oral cavity ---
    "A01AD": {"category": "Cavitate orală",
              "symptoms": ["afte bucale", "stomatită", "gingivită", "iritație gingii"],
              "description": "Tratament local pentru afecțiuni ale cavității orale."},
    "A01AB": {"category": "Cavitate orală",
              "symptoms": ["infecție bucală", "afte", "stomatită"],
              "description": "Antiinfecțios local pentru cavitatea orală."},
    # --- Vitamins & supplements ---
    "A11CC": {"category": "Vitamina D",
              "symptoms": ["deficit vitamina D", "imunitate scăzută", "oase fragile"],
              "description": "Suplimentare cu vitamina D."},
    "A11HA": {"category": "Vitamine",
              "symptoms": ["oboseală", "deficit vitaminic"],
              "description": "Vitamină pentru suplimentare."},
    "A12AX": {"category": "Calciu + vitamine",
              "symptoms": ["deficit calciu", "oase fragile", "osteoporoză prevenție"],
              "description": "Combinație calciu cu vitamina D pentru sănătatea oaselor."},
    "A12BA": {"category": "Suplimente potasiu",
              "symptoms": ["crampe musculare", "deficit potasiu"],
              "description": "Suplimentare cu potasiu."},
    "A12CC": {"category": "Suplimente magneziu",
              "symptoms": ["crampe musculare", "oboseală", "stres", "deficit magneziu"],
              "description": "Suplimentare cu magneziu."},
    # --- Vascular / circulation ---
    "C05CA": {"category": "Insuficiență venoasă",
              "symptoms": ["picioare grele", "varice", "edem picioare", "hemoroizi"],
              "description": "Venotonic pentru insuficiență venoasă cronică."},
    "C05BA": {"category": "Insuficiență venoasă",
              "symptoms": ["varice", "tromboflebită superficială", "hematom"],
              "description": "Tratament topic pentru afecțiuni venoase superficiale și hematoame."},
    # --- Nicotine cessation ---
    "N07BA": {"category": "Renunțare la fumat",
              "symptoms": ["renunțare la fumat", "dependența de nicotină"],
              "description": "Tratament pentru renunțarea la fumat."},
    # --- Emergency contraception ---
    "G03AD": {"category": "Contracepție de urgență",
              "symptoms": ["contracepție de urgență"],
              "description": "Contracepție de urgență după contact sexual neprotejat."},
    # --- Eye drops ---
    "S01GX": {"category": "Alergii oculare",
              "symptoms": ["ochi roșii alergici", "mâncărime ochi", "lacrimare alergică"],
              "description": "Picături oftalmice antialergice."},
    "S01XA": {"category": "Uscăciune oculară",
              "symptoms": ["ochi uscați", "iritație oculară"],
              "description": "Lubrifiant ocular pentru sindrom de ochi uscat."},
    # --- Homeopathic ---
    "XRNIT": {"category": "Homeopate",
              "symptoms": ["tratament homeopat"],
              "description": "Produs homeopat. Eficacitatea nu este demonstrată științific."},
}


def lookup(atc_code: str) -> dict | None:
    if not atc_code:
        return None
    return ATC4_INDICATIONS.get(atc_code[:5])
